---
# tasks file for docker

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Start and Enable Docker
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes

- name: Copy Docker daemon configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: Restart Docker

